const express = require('express');
const cors = require('cors'); 
const connectDB = require('./db');
const authRoutes = require('./routes/authRoutes');
const quizRoutes = require('./routes/quizRoutes');
const errorHandler = require('./middleware/errorHandler'); 
const userRoutes = require('./routes/userRoutes');
require('dotenv').config();
const app = express();
const PORT = process.env.PORT || 5000; 
app.use(cors()); 
app.use(express.json());
app.use(express.static('public')); 
connectDB();
app.use('/api/auth', authRoutes);
app.use('/api/users', userRoutes);
app.use('/api/quizzes', quizRoutes); 
app.use(errorHandler);
app.listen(PORT, () => {
    console.log(`Hey, You want to see my project? Then go to the localhost: ${PORT}`);
});